# Generated by Django 3.0.2 on 2020-01-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('edad', models.PositiveIntegerField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_persona',
            },
        ),
    ]
